<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERD.DatabaseScripts\ERD.DatabaseScripts.csproj" />
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
    <ProjectReference Include="..\WPF.Tools\WPF.Tools.csproj" />
    <ProjectReference Include="..\ERD.Base\ERD.Base.csproj" />
    <ProjectReference Include="..\ERD.Common\ERD.Common.csproj" />
    <ProjectReference Include="..\ERD.Models\ERD.Models.csproj" />
  </ItemGroup>
</Project>