<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyTitle>Report.Web.Presenters</AssemblyTitle>
    <Product>Report.Web.Presenters</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.22.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERD.Base\ERD.Base.csproj" />
    <ProjectReference Include="..\ERD.Common\ERD.Common.csproj" />
    <ProjectReference Include="..\ERD.Models\ERD.Models.csproj" />
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
    <ProjectReference Include="..\IconSet\IconSet.csproj" />
    <ProjectReference Include="..\REPORT.Data\REPORT.Data.csproj" />
    <ProjectReference Include="..\ViSo.Common\ViSo.Common.csproj" />
    <ProjectReference Include="..\ViSo.SharedEnums\ViSo.SharedEnums.csproj" />
  </ItemGroup>
</Project>