<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
    <ProjectReference Include="..\IconSet\IconSet.csproj" />
    <ProjectReference Include="..\ViSo.Common\ViSo.Common.csproj" />
    <ProjectReference Include="..\ViSo.SharedEnums\ViSo.SharedEnums.csproj" />
  </ItemGroup>
</Project>