<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>ViSo_nice.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ViSo_nice.ico" />
  </ItemGroup>
</Project>