<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr" Version="3.5.0.2" />
    <PackageReference Include="bootstrap" Version="3.4.1" />
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="Microsoft.AspNet.FriendlyUrls" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNet.FriendlyUrls.Core" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNet.ScriptManager.MSAjax" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNet.ScriptManager.WebForms" Version="5.0.0" />
    <PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.477" />
    <PackageReference Include="Modernizr" Version="2.8.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WebGrease" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.3.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Default.aspx.cs">
      <DependentUpon>Default.aspx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="Default.aspx.designer.cs">
      <DependentUpon>Default.aspx</DependentUpon>
    </Compile>
    <Compile Update="Global.asax.cs">
      <DependentUpon>Global.asax</DependentUpon>
    </Compile>
    <Compile Update="ReportFilters.aspx.cs">
      <DependentUpon>ReportFilters.aspx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="ReportFilters.aspx.designer.cs">
      <DependentUpon>ReportFilters.aspx</DependentUpon>
    </Compile>
    <Compile Update="Site.Master.cs">
      <DependentUpon>Site.Master</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="Site.Master.designer.cs">
      <DependentUpon>Site.Master</DependentUpon>
    </Compile>
    <Compile Update="Site.Mobile.Master.cs">
      <DependentUpon>Site.Mobile.Master</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="Site.Mobile.Master.designer.cs">
      <DependentUpon>Site.Mobile.Master</DependentUpon>
    </Compile>
    <Compile Update="ViewSwitcher.ascx.cs">
      <DependentUpon>ViewSwitcher.ascx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="ViewSwitcher.ascx.designer.cs">
      <DependentUpon>ViewSwitcher.ascx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="Web.Debug.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
    <None Include="Web.Release.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERD.Base\ERD.Base.csproj" />
    <ProjectReference Include="..\ERD.Common\ERD.Common.csproj" />
    <ProjectReference Include="..\ERD.DatabaseScripts\ERD.DatabaseScripts.csproj" />
    <ProjectReference Include="..\ERD.Models\ERD.Models.csproj" />
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
    <ProjectReference Include="..\IconSet\IconSet.csproj" />
    <ProjectReference Include="..\REPORT.Builder\REPORT.Builder.csproj" />
    <ProjectReference Include="..\REPORT.Data\REPORT.Data.csproj" />
    <ProjectReference Include="..\Report.Web.Presenters\Report.Web.Presenters.csproj" />
    <ProjectReference Include="..\ViSo.Common\ViSo.Common.csproj" />
    <ProjectReference Include="..\ViSo.SharedEnums\ViSo.SharedEnums.csproj" />
  </ItemGroup>
</Project>