<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="PdfSharp.Xps" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERD.Base\ERD.Base.csproj" />
    <ProjectReference Include="..\ERD.Common\ERD.Common.csproj" />
    <ProjectReference Include="..\ERD.DatabaseScripts\ERD.DatabaseScripts.csproj" />
    <ProjectReference Include="..\ERD.Models\ERD.Models.csproj" />
    <ProjectReference Include="..\GeneralExtensions\GeneralExtensions.csproj" />
    <ProjectReference Include="..\IconSet\IconSet.csproj" />
    <ProjectReference Include="..\REPORT.Data\REPORT.Data.csproj" />
    <ProjectReference Include="..\ViSo.Common\ViSo.Common.csproj" />
    <ProjectReference Include="..\ViSo.Dialogs\ViSo.Dialogs.csproj" />
    <ProjectReference Include="..\ViSo.SharedEnums\ViSo.SharedEnums.csproj" />
    <ProjectReference Include="..\WPF.Tools\WPF.Tools.csproj" />
  </ItemGroup>
</Project>